project_id: 582949
base_path: /
preserve_hierarchy: true

files:
  -
    source: /*.pot
    translation: /%locale_with_underscore%/LC_MESSAGES/%filename%.po
    ignore: ['**.js', '**.css']
    escape_quotes: 2
    escape_special_characters: 1
    skip_untranslated_strings: true
