project_id: 582949
base_path: .
preserve_hierarchy: false

files:
  -
    source: /locales/KanboardNG.pot
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/KanboardNG.po
    languages_mapping:
      locale_with_underscore:
        af: af
        an: an
        ar: ar
        az: az
        be: be
        bg: bg
        bn: bn
        bs: bs
        ca: ca
        ckb: ckb
        co: co
        cs: cs
        da: da
        de: de
        el: el
        et: et
        eu: eu
        fa: fa
        fi: fi
        fr: fr
        ga-IE: ga
        gl: gl
        he: he
        hr: hr
        hu: hu
        hy-AM: hy
        id: id
        is: is
        it: it
        ja: ja
        ka: ka
        kab: kab
        kk: kk
        ko: ko
        ku: ku
        lt: lt
        lv: lv
        ms: ms
        nb: nb
        nl: nl
        oc: oc
        pl: pl
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sq: sq
        sr: sr
        tg: tg
        th: th
        tr: tr
        uk: uk
        uz: uz
        vi: vi
        es-ES: es
        pa-IN: pa
        sv-SE: sv
        zh-CN: zh_CN
        zh-TW: zh_TW
