name: "Crowdin Project Stats"

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    
jobs:
  updatestats:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: get stats from URI
      run: wget -qN https://badges.awesome-crowdin.com/stats-14158123-582949.json -O assets/crowdin-stats.json
      #run: curl -s -o assets/crowdin-stats.json https://badges.awesome-crowdin.com/stats-14158123-582949.json

    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v4
