name: "Update Translation"

# runs on push to "main" and only for "*.pot" files in root
on: 
  push:
    paths:
      - "*.pot"
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  CrowdinTasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout gettext-locale
        uses: actions/checkout@v3

      - name: push new strings
        uses: crowdin/github-action@v1
        with:
          config: 'crowdin.yaml'
          project_id: ${{ vars.CROWDIN_PROJECT }}
          token: ${{ secrets.CROWDIN_TOKEN }}
          upload_sources: true
          upload_translations: false
          download_translations: true
          push_translations: false

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
